#!/bin/bash

help=`echo $@ | grep "\(--help\|-h\)"`
if [ ! -z "$help" ]
then
	echo "alt_tbss_4.sh"
	echo "This script generates group files and then prepares data already projected onto the skeletons for display"
	echo "Either set a design file in the stats folder with design_ttest2 before running this. Alternatively, you may"
	echo "provide a file entitles groupfile.csv in the main folder, which this script will then convert into the proper"
	echo "design files. If you run this script without either of these files, a blank groupfile.csv will be generated,"
	echo "and you may edit that."
	echo "Usage:"
	echo " -h --help : Display this message"
	exit
fi


thresh=$1
measure=$2

if [ ! -e "stats/design.mat" ]
then
	if [ -e "groupfile.csv" ]
	then
		${FSLDIR}/bin/design_ttest2 design `ls *.nrrd | wc -l` 0
		echo "/NumWaves 2" > stats/design.mat
		echo "/NumPoints `cat groupfile.csv | wc -l`" >> stats/design.mat
		echo "/PPheights 1 1" >> stats/design.mat
		echo "/Matrix" >> stats/design.mat
		for i in `cat groupfile.csv`
		do
			num=`echo $i | sed 's/[^,]*,1,/1 0/g' | sed 's/[^,]*,0,/0 1/g'`
			echo $num >> stats/design.mat
		done
	else
		echo "Please provide either a design.mat and design.con file in the stats folder"
		echo "Or write groupfile.csv in the main folder. This script will now generate a"
		echo "groupfile.csv with all subjects in the same group. If you wish to edit this"
		echo "file, change the 0's to 1's for the subjects in a different group."
		
		ls *.nrrd | sed 's/\.nrrd/\.nrrd,0,/g' > groupfile.txt
		exit
	fi
fi

if [ ! -e "stats/design.con" ]
then
	echo "Please provide a design.con file in the stats folder. This, along with design.mat,"
	echo "is generated by running design_ttest2"
	exit
fi

randomise -i stats/all_AD_skeletonised -o stats/tbss -m stats/mean_FA_skeleton_mask -d stats/design.mat -t stats/design.con -n 5000 -c 3 -V

fslview stats/mean_FA stats/mean_FA_skeleton -l Green -b 0.2,0.8 stats/tbss_tstat1 -l Red-Yellow -b 3,6 stats/tbss_tstat2 -l Blue-Lightblue -b 3,6
fslview stats/mean_FA stats/mean_FA_skeleton -l Green -b 0.2,0.8 stats/tbss_maxc_tstat1 -l Red-Yellow -b 3,6 stats/tbss_maxc_tstat2 -l Blue-Lightblue -b 3,6
